### ISSUE TITLE
Failed to switch context when using separate kubeconfig files

### ISSUE THREAD

**Issue by islameldigwi** [aabouzaid/kubech#3]
I am using the $KUBECONFIG environment variables to provide path for kubeconfig files (kubeconfig file per cluster)

example:

I have 3 different kubeconfig files: sandbox, staging and production

it seems running `kubechc` is able to list the context, but then it fails to switch.

```
$ kubechc
sandbox
staging
production
```

but then trying to switch context
```
$kubechc production
W0505 17:04:28.166764   49998 loader.go:223] Config not found: /Users/islamshehata/.kube/config
error: cannot locate context production
error: no context exists with the name: "production"
```

kubectx works fine with that setup.

**Comment by aabouzaid** [comment]
@schehata do you use 1 `KUBECONFIG` var for all files or 1 `KUBECONFIG` per file?
If you export only one file, then check out the latest [change](https://github.com/aabouzaid/kubech/commit/43364720ea24b36211c4eb9a22d098f478121406), it should fix this issue.

**Comment by aabouzaid** [comment]
This is now supported by storing config files in the path of `KUBECONFIG_SRC_DIR` var (by default is `$HOME/.kube/config.src.d`).
